#!/usr/bin/env bash

symbol="${1:-"BTCUSD"}"
chart_url="https://hitbtc.com/chart/$symbol"
api_url="https://api.hitbtc.com/api/1/public/$symbol/ticker"

[ "$BLOCK_BUTTON" = "1" ] && xdg-open "$chart_url"


if ! out="$(curl -s "$api_url")"; then
    echo "error"
    echo "error"
    echo "#ff0000"
    exit 0
fi

echo "$out" | jq -r '.["last"]'
