#!/usr/bin/env bash

bitcoinity_url="http://bitcoinity.org/markets/hitbtc/USD"
api_url="https://www.bitstamp.net/api/ticker/"
symbol="${1:-"BTCUSD"}"
api_url="https://api.hitbtc.com/api/1/public/$symbol/ticker"

[ "$BLOCK_BUTTON" = "1" ] && xdg-open "$bitcoinity_url"


if ! out="$(curl -s "$api_url")"; then
    echo "error"
    echo "error"
    echo "#ff0000"
    exit 0
fi

echo "$out" | jq -r '.["last"]'
