#!/bin/bash

# Percentage at and bellow which the color is red.
# default is 10%
ALERT_LOW="${1:-10}"

awk -v alert_low=$ALERT_LOW '
/MemAvailable/  { avail = $2 }
/MemTotal/      { total = $2 }
END {
    printf "%.2f\n", avail /1024/1024
    printf "%.2f\n", avail /1024/1024
    if ( avail <= (alert_low/100)*total ) print "#ff0000"
}
' /proc/meminfo
